FROM denoland/deno:alpine

WORKDIR /app

# The user is running the tests from the context of the tests dir
# so we copy api_test.ts and deno.json into the image
COPY api_test.ts .
COPY deno.json .

# Environment variables will be passed via docker-compose
CMD ["test", "--allow-all", "api_test.ts"]
